<a href="https://colab.research.google.com/github/hjchoi0207/Python_Data_and_Image/blob/master/04.%20Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy를 이용해 배열을 다양한 방법으로 활용할 수 있다.

1. 배열 초기화 및 타입 선언
2. 배열 가로로 합치기
3. 배열 형태 바꾸기
4. 배열 세로로 합치기
5. 배열 나누기

In [19]:
import numpy as np

In [2]:
list_data = [1,2,3]

In [3]:
array = np.array(list_data) #numpy화 해줌으로써 리스트보다 다양한 함수들을 호출할 수 있다.

In [8]:
array1 = np.arange(4) # 0부터 4-1 까지 만들기
print(array1)

[0 1 2 3]


In [9]:
array2 = np.zeros((4,4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
array3 = np.ones((3,3), dtype = str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [11]:
array4 = np.random.randint(0,10,(3,3)) # 3x3배열에 0~9사이의 정수를 채워라
print(array4) 

[[7 1 9]
 [1 7 5]
 [0 4 8]]


In [12]:
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열 생성
array5 = np.random.normal(0,1,(3,3))
array5

array([[-0.83016236,  0.37302925,  0.28529095],
       [-0.83202273,  0.79551957, -0.42894083],
       [-0.58509304,  0.63426795,  0.14524806]])

**Numpy 배열 합치기**

In [13]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.concatenate([array1, array2]) # 배열을 합치는 concatenate 함수

In [14]:
print(array3.shape) # 몇 개의 데이터가 담겨있는지 확인

(6,)


In [15]:
print(array3)

[1 2 3 4 5 6]


**Numpy 배열 형태 바꾸기 및 세로로 합치기**

In [16]:
array3.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
array1 = np.arange(4).reshape(1,4)
array2 = np.arange(8).reshape(2,4)
print(array1)
print(array2)

[[0 1 2 3]]
[[0 1 2 3]
 [4 5 6 7]]


In [22]:
array3 = np.concatenate([array1, array2], axis = 0) #세로로 합치기 위한 옵션 axis = 0
array3

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

**Numpy 배열 나누기**

In [25]:
array = np.arange(8).reshape(2,4) #0~7까지 2x4 배열에 생성
print(array)
left, right = np.split(array, [2], axis = 1) # split 함수를 이용하여 [0,1,2,3]열 중 2열을 기준으로 좌 우로 나눈다
print(left.shape)
print(right.shape)

[[0 1 2 3]
 [4 5 6 7]]
(2, 2)
(2, 2)


In [26]:
print(left)
print(right)

[[0 1]
 [4 5]]
[[2 3]
 [6 7]]
