<a href="https://colab.research.google.com/github/hjchoi0207/Python_Data_and_Image/blob/master/04.%20Numpy%EC%9D%98%20%EA%B8%B0%EB%B3%B8%20%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list_data = [1,2,3]

In [3]:
array = np.array(list_data) #numpy화 해줌으로써 리스트보다 다양한 함수들을 호출할 수 있다.

In [8]:
array1 = np.arange(4)
print(array1)

[0 1 2 3]


In [9]:
array2 = np.zeros((4,4), dtype=float)
print(array2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
array3 = np.ones((3,3), dtype = str)
print(array3)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]


In [11]:
array4 = np.random.randint(0,10,(3,3)) # 3x3배열에 0~9사이의 정수를 채워라
print(array4) 

[[7 1 9]
 [1 7 5]
 [0 4 8]]


In [12]:
# 평균이 0이고 표준편차가 1인 표준 정규를 띄는 배열 생성
array5 = np.random.normal(0,1,(3,3))
array5

array([[-0.83016236,  0.37302925,  0.28529095],
       [-0.83202273,  0.79551957, -0.42894083],
       [-0.58509304,  0.63426795,  0.14524806]])