<a href="https://colab.research.google.com/github/hjchoi0207/Python_Data_and_Image/blob/master/05.%20Numpy%20%EA%B8%B0%EB%B3%B8%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy의 기본 연산

**Numpy 스칼라연산**

In [3]:
import numpy as np
array = np.random.randint(1,10, size = 4).reshape(2,2) # 1부터 9 사이의 정수 4개를 생성하고 형태변환하라.
print(array)

[[8 1]
 [3 9]]


In [4]:
res_array = array * 10
res_array

array([[80, 10],
       [30, 90]])

**서로 다른 형태의 Numpy 연산** <hr/>
브로드캐스트 : 형태가 다른 배열을 연산할 수 있도록 배열 형태를 동적으로 변환

In [9]:
import numpy as np

array1 = np.arange(4).reshape(2,2) # 0 부터 3 까지의 정수를 생성하여 2x2 배열 형태로 형변환 하라
array2 = np.arange(2) # 1 x 2
# array2 = np.arange(2).reshape(2,1)  # 2 x 1 

print(array1)
print(array2)

array3 = array1 + array2 #array2의 정수 배수는 array1에 부합되기 때문에 연산가능하다.
print(array3)

[[0 1]
 [2 3]]
[0 1]
[[0 2]
 [2 4]]


In [17]:
import numpy as np

array1 = np.arange(0,8).reshape(2,4)
array2 = np.arange(0,8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis = 0)
array4 = np.arange(0,4).reshape(4,1)
print(array3)
print(array4)
print(array3 + array4)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


**Numpy의 마스킹 연산 - 각 원소에 대해 체크하는 것**

In [25]:
import numpy as np

array1 = np.arange(16).reshape(4,4)
print(array1)

array2 = array1 < 10  #마스킹 연산 수행
print(array2)
array1[array2] = 100  # True 인 원소들에 대해서만 연산 수행
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


**Numpy의 집계함수**

In [29]:
import numpy as np

array = np.arange(16).reshape(4,4)
print(array)
print("csum : ", np.sum(array, axis = 0))  # 열의 원소를 더한 값
print("max : ", np.max(array))
print("min : ", np.min(array))
print("sum : ", np.sum(array))
print("mean : ", np.mean(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
csum :  [24 28 32 36]
max :  15
min :  0
sum :  120
mean :  7.5
