<a href="https://colab.research.google.com/github/hjchoi0207/Python_Data_and_Image/blob/master/06.%20Numpy%EC%9D%98%20%ED%99%9C%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**파이썬 데이터 분석과 이미지 처리**   
Numpy의 저장 및 불러오기 : save, load

In [4]:
import numpy as np

#save 함수와 load 함수로 단일 객체 저장 및 불러오기
array = np.arange(0, 10)
np.save('saved.npy', array)

result = np.load('saved.npy')
print(result)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# 복수 객체 저장 및 불러오기
array1 = np.arange(0,10)
array2 = np.arange(10,20)

#np.save('saved.npy',(array1,array2))
np.savez('saved.npz', arr1=array1, arr2=array2)
data = np.load('saved.npz')
res1 = data['arr1']    #이름 인덱스로 접근 가능
res2 = data['arr2']
print(res1)
print(res2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


**Numpy 원소의 정렬**   
sort() 와 행기준 sort(axis = 0)

In [13]:
array = np.array([4,2,1,8,9])
array.sort()
print(array)
print(array[::-1])

[1 2 4 8 9]
[9 8 4 2 1]


In [17]:
# 각 열을 기준으로 정렬
array = np.array([[8,2,1,9,5],[3,7,2,1,4]]) #2차원 배열
print(array)
array.sort(axis = 0)
print(array)

[[8 2 1 9 5]
 [3 7 2 1 4]]
[[3 2 1 1 4]
 [8 7 2 9 5]]


In [19]:
# 균일한 간격으로 데이터 생성
array = np.linspace(0, 10, 5)
print(array)

[ 0.   2.5  5.   7.5 10. ]


**np.random.randint() : 랜덤값 생성**   
**np.random.seed() : 시드 고정**

In [23]:
# 난수의 재연 (항상 동일)
np.random.seed(7) # 시드 값을 동일하게 하면 항상 같은 난수 발생
print(np.random.randint(0,10,(2,3)))

[[4 9 6]
 [3 3 7]]


**copy() : 함수를 이용한 값에의한 참조**

In [25]:
# 배열 객체 복사
array2 = array1
array2[0] = 100
print(array1)   # array2 값을 변경하면  array1 값도 바뀐다.

[100   1   2   3   4   5   6   7   8   9]


In [26]:
array1 = np.arange(0,10)
array2 = array1.copy()
array2[0] = 100
print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


**unique(array) : 중복원소 제거**

In [27]:
array = np.array([1,2,2,3,4,4,4,5,5])
print(np.unique(array))

[1 2 3 4 5]
